### PR TITLE
Fix build error when TLS is disabled

### PR DESCRIPTION
**Pull request by jbg**

### CODE REVIEW

**Comment by Keruspe** [comment]
Thanks, should definitely be covered by CI

**Comment by jbg** [comment]
no worries! i have just noticed there are actually some other build errors with tls disabled, i'm looking into those now and can update this PR.

**Comment by jbg** [comment]
done, although i'm not 100% happy with all the:

```
#[cfg(any(feature = "native-tls", feature = "openssl", feature = "rustls"))]
```

since if you add any more TLS backends they'll all have to be updated. maybe you have a better idea for how to handle that?

**Comment by jbg** [comment]
I tidied it up a bit, removed most of the `cfg(any(...))` and re-introduced a public type that shouldn't have been removed, and squashed the commits into one.

**Comment by Keruspe** [comment]
Thanks, cherry-picked as 0d33b2891b1090648d55c47ae9adb3a533d88456 without the `cfg(any(...))` and added a couple of followup commits

**Comment by Keruspe** [comment]
0.5.0 published

**Pull request closed without merging**
